= Streaming Movies Ratings
Viktor Gamov
2019-05-30 14:00
:imagesdir: ../images
:icons:
:keywords:
:toc:
:experimental:
:commandkey: &#8984;

.TL;DR
A full source code published in `gAmUssA/streaming-movie-ratings-min-0519` repository footnote:[https://github.com/gAmUssA/streaming-movie-ratings-min-0519]

.Revisions history
[width="70%",cols="",options="header"]
|===
|Version    |Date   | Comments
|*v1.0*     |05/30/2010 | Initial revision
|===

toc::[]

To be successful in executing all exercises, you need to have following installed.

* Git
* JDK (min JDK 8)
** Recommended way
*** Install https://sdkman.io/install[sdkman]
*** `sdk list java`
*** `sdk install java <verison-provider>` e.g. `sdk install java 8.0.212-librca`
* Install https://www.jetbrains.com/idea/download/[IntelliJ IDEA Community Edition]

* Get example from GitHub
** If you will follow steps below you should checkout only directory that has source code relevant to this post.
+

[source,bash]
----
mkdir ~/temp/demo-scene
cd ~/temp/demo-scene
git clone https://github.com/gAmUssA/streaming-movie-ratings-min-0519 
----
+

* import gradle the project to IntelliJ IDEA

== Demo playbook

=== Build everything (+Smoke test)

----
./gradlew clean build
----

NOTE: You may need to modify proxy settings in `gradle/wrapper/gradle-wrapper.properties`


WARNING: For each application you will be running from IntelliJ, you need to provide a full location of configuration file (e.g. `/usr/share/kafka-streams/configuration/dev.properties`) as program argument. 
The application with throw an error otherwise.

=== Populate Movies and Rating Information

Run `src/main/groovy/MovieLoader` to populate Movies.

=== Run Streaming Movie Demo

Run `StreamsDemo` IntelliJ `Run..` command.

=== Generate test load

Run `src/main/groovy/RawRatingsStreamer` to generate test load.

=== OPTIONAL if KSQL available: Consume result with KSQL UI in Control Center

* Open Control Center. 
Local page is http://localhost:9021
* open KSQL panel and switch to «Query Editor.»
+

[source,sql]
----
CREATE TABLE RATED_MOVIES \
    (MOVIE_ID BIGINT,\
     TITLE VARCHAR,\
     RELEASE_YEAR BIGINT,\
     RATING DOUBLE)\
WITH (KAFKA_TOPIC='rated-movies',VALUE_FORMAT='AVRO', KEY = 'movie_id'); --<1>

select TITLE, RATING  from RATED_MOVIES where MOVIE_ID=362; --<2>
----
<1> Create a table with Movie ratings. You need to use your `rated-movies` topic
<2> Find rating for Lethal Weapon (`movie_id=362`)

=== Reset your application

In case of problems, you can always reset state of the applications.

----
kafka-streams-application-reset --application-id kafka-films --bootstrap-servers localhost:9092 --config-file ~/.ccloud/config.local --input-topics raw_movies,raw_ratings
----
